package com.carevia.shared.constant;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_COMPLETED,
    BOOKING_EXPIRED,
    ORDER_CREATED,
    ORDER_PAID,
    ORDER_PROCESSING,
    ORDER_COMPLETED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_SUSPENDED,
    SYSTEM
}
