server:
  port: 8081

jwt:
  secret: carevialocaljwtsecretcarevia2026keyv1v2v3v4v5v6
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:2592000}

spring:
  application:
    name: carevia-backend

  datasource:
    # Nếu chạy Docker, hãy đổi 'localhost' thành 'postgres'
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/carevia?options=-c%20timezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:carevia_user}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    # Khi dùng Docker, ta nên ép Dialect luôn để tránh Hibernate mất công tìm kiếm metadata khi kết nối chưa ổn định
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Để Hibernate tự động nhận diện Dialect (tránh cảnh báo thừa)
    hibernate:
      ddl-auto: update # Tự động cập nhật bảng mà không xóa dữ liệu
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:bichla12005@gmail.com}
    password: ${MAIL_PASSWORD:jxkrprzuruyccsri}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Cấu hình để không bị lỗi khi upload ảnh avatar dung lượng lớn
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Cấu hình MinIO
minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:carevia_minio_secret}
  bucket: ${MINIO_BUCKET_NAME:carevia-products}

# Cấu hình ZaloPay
zalopay:
  app-id: ${ZALOPAY_APP_ID:2553}
  key1: ${ZALOPAY_KEY1:9ph31jnse3ke2urj1u939as6p02m5ba8}
  key2: ${ZALOPAY_KEY2:Iyz2habByrTH08sS79ESt7nnEnu9u788}
  endpoint: ${ZALOPAY_ENDPOINT:https://zalopay.vn}

# Cấu hình App (Avatar & Websocket)
app:
  avatar:
    folder: ${APP_AVATAR_FOLDER:avatars}
    max-size-bytes: ${APP_AVATAR_MAX_SIZE:5242880} # 5MB
    default-url: "${APP_DEFAULT_AVATAR_URL:https://cloudinary.com}"
  websocket:
    endpoint: "/ws-notification"
    topic: "/topic/messages"

# Cấu hình Cloudinary
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:dcisx0vss}
  api_key: ${CLOUDINARY_API_KEY:853988661563551}
  api_secret: ${CLOUDINARY_API_SECRET:enx1WB_Hsff4ebdfUnnYBAwOawI}

# Ẩn các log cảnh báo không cần thiết về thư viện cũ
logging:
  level:
    org.apache.commons.logging: ERROR
    org.springframework.security: DEBUG
